# Generated by Django 4.1.7 on 2023-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='donations',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
    ]
